POST http://localhost:8081/event
Content-Type: application/json

{
  "name": "test",
  "rss_feed": "https://news.demo.inception.cloud/inception/RunningOrder/RunningOrder.rss?id=3962"
}

###
GET http://localhost:8081/

###

GET http://localhost:8081/register
Content-Type: application/json

{
  "event_id": 1
}

###
GET http://localhost:8081/question
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTIwMzY2MTcsIm5iZiI6MTYxMjAzNjYxNywianRpIjoiNjY2NzNiNjItZWJhZC00NmRjLTkxMTMtMWNkZDgxNTZlMzZlIiwiaWRlbnRpdHkiOjMsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.zuS9b6gJDRh0iNoAgVzsiW95aN1G6n-fyyiHNuKAObE

###

DELETE http://localhost:8081/event/2

###
GET http://localhost:8081/test
Content-Type:  application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTIwNjk2NjksIm5iZiI6MTYxMjA2OTY2OSwianRpIjoiZWMzNWQzN2QtNWNmNC00OTJjLWI0OTctZWVjZmEyODg4MzllIiwiaWRlbnRpdHkiOjEsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.rnO8xxXI5XDBz7-pqbNTH8cxJxly6lx2hpDHBLk--mk

{
  "text": "barack obama"
}
