POST http://localhost:8081/event
Content-Type: application/json

{
  "name": "test",
  "rss_feed": "https://news.demo.inception.cloud/inception/RunningOrder/RunningOrder.rss?id=3962"
}

###
GET http://localhost:8081/

###

GET http://localhost:8081/register
Content-Type: application/json

{
  "event_id": 1
}

###
GET http://localhost:8081/question
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTIwOTUxMTAsIm5iZiI6MTYxMjA5NTExMCwianRpIjoiZDllZDA2NzQtYzY4NS00MmE0LTk0M2YtNjJhNTM0ZDdjN2E4IiwiaWRlbnRpdHkiOjMsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.XMEIp5lqIaE8Wc3UosR85uYKnxtzxbOpPF4k2swT5-s

###

DELETE http://localhost:8081/event/2

###
GET http://localhost:8081/test
Content-Type:  application/json
Authorization: Bearer eyJ0eXAiOiJKV1QiLCJhbGciOiJIUzI1NiJ9.eyJpYXQiOjE2MTIwOTUxMTAsIm5iZiI6MTYxMjA5NTExMCwianRpIjoiZDllZDA2NzQtYzY4NS00MmE0LTk0M2YtNjJhNTM0ZDdjN2E4IiwiaWRlbnRpdHkiOjMsImZyZXNoIjpmYWxzZSwidHlwZSI6ImFjY2VzcyJ9.XMEIp5lqIaE8Wc3UosR85uYKnxtzxbOpPF4k2swT5-s

{
  "text": "barack obama"
}
